events {
    worker_connections 1024;
}

http {
    # Rate Limiting: Maksimal 10 request/detik per IP
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    upstream auth_service { server auth-service:3000; }
    upstream transaction_service { server transaction-service:3000; }
    upstream config_service { server config-service:3000; }

    server {
        listen 80;

        # Terapkan rate limit dengan burst 5
        limit_req zone=api_limit burst=5 nodelay;

        # Route Auth Service
        location /api/v1/auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Route Transaction Service (Open API)
        location /api/v1/transactions/ {
            proxy_pass http://transaction_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Route Config Service
        location /api/v1/config/ {
            proxy_pass http://config_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
