apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: ghcr.io/andalusia-idea/transaction-service:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "120Mi"
          limits:
            cpu: "1000m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: production
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
